# Generated by Django 5.0.3 on 2024-04-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='equipment_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('house_type', models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], max_length=4)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rentability', models.CharField(blank=True, choices=[('partial', 'Partially Rentable'), ('full', 'Fully Rentable')], max_length=7, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('number_of_salons', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.equipment')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.house')),
            ],
            options={
                'unique_together': {('house', 'equipment')},
            },
        ),
        migrations.AddField(
            model_name='house',
            name='equipment',
            field=models.ManyToManyField(related_name='houses', through='real_estate.HouseEquipment', to='real_estate.equipment'),
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='house_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='real_estate.house')),
            ],
        ),
    ]
