# Generated by Django 5.0.3 on 2024-04-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='monthly_cost',
        ),
        migrations.RemoveField(
            model_name='house',
            name='payment_duration_months',
        ),
    ]
