# Generated by Django 5.0.3 on 2024-04-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_remove_house_monthly_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='number_of_toilets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
