# Generated by Django 5.0.3 on 2024-04-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_house_number_of_toilets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='icon',
        ),
        migrations.AddField(
            model_name='equipment',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG code for the icon.', null=True),
        ),
    ]
