# Generated by Django 5.0.3 on 2024-04-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_alter_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
