# Generated by Django 5.0.3 on 2024-04-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_houseimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseimage',
            name='replaced',
            field=models.BooleanField(default=False),
        ),
    ]
