# Generated by Django 5.0.3 on 2024-04-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_houseimage_replaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('expected_result', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
