# Generated by Django 5.0.3 on 2024-04-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_searchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='floor_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
