# Generated by Django 5.0.3 on 2024-04-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0014_alter_house_floor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
