# Generated by Django 5.0.3 on 2024-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0016_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
