# Generated by Django 5.0.3 on 2024-06-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0023_alter_synonyms_original_word_alter_synonyms_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255),
        ),
    ]
