# Generated by Django 5.0.3 on 2024-06-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0024_alter_house_description_alter_house_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='text',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
    ]
